# Generated by Django 5.0.8 on 2024-08-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_manufactural', models.BooleanField(default='yes')),
                ('supplier_name', models.CharField(max_length=50)),
                ('supplier_phone', models.CharField(max_length=20)),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_phone', models.CharField(max_length=20)),
            ],
        ),
    ]
